Генерация данных
htmlacademy-javascript/2058165-kekstagram-28 pull request #3
Opened 2023-03-01 17:48 UTC by ya-broccoli

2023-03-01 18:36 UTC, AlexMasterov requested changes
Нужно немного доработать.

2023-03-01 18:36 UTC, AlexMasterov commented on js/main.js
> +  comments: createComment(1, 3),
См. задание:
> `comments`, массив объектов — список комментариев

<details>
<summary>main.js</summary>

https://github.com/htmlacademy-javascript/2058165-kekstagram-28/blob/d68cebcc1ea4e85ac5bd259d8629c8eb270409d0/js/main.js#L68-L73
</details>

comment`s`: `createComment`(1, 3),

Функция `createComment` создает и возвращает _один_ объект с данными комментария, а нужен _массив_ таких объектов.

> \+ название свойства comment`s` во множ. числе указывает, что в простом случае значением должен быть массив

2023-03-01 18:36 UTC, AlexMasterov commented on js/main.js
> +  comments: createComment(1, 3),
<details>
<summary>main.js</summary>

https://github.com/htmlacademy-javascript/2058165-kekstagram-28/blob/d68cebcc1ea4e85ac5bd259d8629c8eb270409d0/js/main.js#L68-L73
</details>

comments: createComment(`1, 3`),

Функция `createComment` вызывается с двумя аргументами, значения которых не будут использованы, потому что у функции нет параметров.

Нужно удалить неиспользуемые аргументы и далее быть внимательней.

[Б12](https://up.htmlacademy.ru/javascript/28/criteries#b12)
> В коде проекта нет файлов, модулей и частей кода, которые не используются

2023-03-01 18:36 UTC, AlexMasterov commented on js/main.js
> +  url: `photos/${generateUrl()}.jpg`,
<details>
<summary>main.js</summary>

https://github.com/htmlacademy-javascript/2058165-kekstagram-28/blob/d68cebcc1ea4e85ac5bd259d8629c8eb270409d0/js/main.js#L66
</details>

url: photos/${`generateUrl()`}.jpg,

Функция `generateUrl` на самом деле генерирует случайное число, которое здесь используются как часть `url`.

Неудачное название функции, которое вводит в заблуждение.

[Б6.](https://up.htmlacademy.ru/javascript/28/criteries#b6)
> Название функции или метода должно быть глаголом и соответствовать действию, которое выполняет функция или метод

2023-03-01 18:36 UTC, AlexMasterov commented on js/main.js
> +  message: `${getRandomArrayElement(MESSAGES)}`,
message: ``${`getRandomArrayElement(MESSAGES)`}``,

В таком случае шаблонные строки избыточны (неуместны):

```diff
- message: `${getRandomArrayElement(MESSAGES)}`,
+ message: getRandomArrayElement(MESSAGES),
```

2023-03-01 18:36 UTC, AlexMasterov commented on js/main.js
> +const similarPhotoDescriptions = () => Array.from({length: PHOTO_DESCRIPTIONS_COUNT}, createPhotoDescription);
`similarPhotoDescriptions`

> См. https://github.com/htmlacademy-javascript/2058165-kekstagram-28/pull/2#discussion_r1116236146 

[Б6](https://up.htmlacademy.ru/javascript/28/criteries#b6) 
> Название функции или метода содержит глагол [_в начале_]

2023-03-01 18:36 UTC, AlexMasterov commented on js/main.js
> +function createRandomIdFromRangeGenerator (min, max) {
`function` createRandomIdFromRangeGenerator

[Д5](https://up.htmlacademy.ru/javascript/28/criteries#d5) 
> Все функции объявлены единообразно.

> При объявлении функций используются стрелочные функции

2023-03-01 18:36 UTC, AlexMasterov commented on js/main.js
> +      return null;
Такая функция возвращает значение двух очень разных типов: `number` и `null` (= no _object_ value).

2023-03-02 18:59 UTC, ya-broccoli commented on js/main.js
> +  message: `${getRandomArrayElement(MESSAGES)}`,
👀

2023-03-02 19:12 UTC, AlexMasterov commented
👍🏻

2023-03-02 19:12 UTC, merged