Отрисуй меня полностью
htmlacademy-javascript/2058165-kekstagram-28 pull request #5
Opened 2023-03-16 16:52 UTC by ya-broccoli

Саша, добрый вечер! 
Мне нужна помощь.
Я сделала домашку, но что-то пошло не так(( и я не понимаю, что именно делаю неправильно.
Количество лайков, коментов и описание, вроде нормально сработали, а вот сами фотки не отрисовываются.
Посмотрите, пожалуйста, где ошибка.
У меня уже голова гудит, ничего не соображаю. 

---
:mortar_board: [Отрисуй меня полностью](https://up.htmlacademy.ru/javascript/28/user/2058165/tasks/12)

:boom: https://htmlacademy-javascript.github.io/2058165-kekstagram-28/5/

2023-03-18 13:31 UTC, AlexMasterov requested changes
Нужно немного доработать.

2023-03-18 13:31 UTC, AlexMasterov commented on js/thumbnails.js
> +    thumbnailElement.querySelector('.picture__img').alt = photo.description;
<details>
<summary>/thumbnails.js</summary>

https://github.com/htmlacademy-javascript/2058165-kekstagram-28/blob/4ebe36e7b999b071e1fafab20e9ad2b5d25d675c/js/thumbnails.js#L16-L18
</details>

3x `thumbnailElement.querySelector('.picture__img')`

Нужно найти DOM-элемент один раз, сохранить в переменную, и уже через неё (пере)использовать в функции.

[Д21](https://up.htmlacademy.ru/javascript/28/criteries#d21) 
> Поиск элементов по селекторам делается минимальное количество раз, после этого ссылки на элементы сохраняются

2023-03-18 13:31 UTC, AlexMasterov commented on js/thumbnails.js
> +const pictureListFragment = document.createDocumentFragment();
Сейчас фрагмент создается вне функции `renderThumbnails` и переиспользуется внутри. Таким образом, повторный вызов функции будет приводить к накоплению DOM-элементов с фото во фрагменте, а при его добавление в DOM (браузер) фото будут дублироваться. 

Нужно создавать фрагмент внутри функции, чтобы при её вызове он всегда был новым и тем самым пустым.

> Переиспользовать фрагмент с очисткой избыточно. Проще создавать новый прямо в функции

2023-03-18 13:31 UTC, AlexMasterov commented on js/main.js
> +renderThumbnails();
<details>
<summary>thumbnails.js</summary>

https://github.com/htmlacademy-javascript/2058165-kekstagram-28/blob/4ebe36e7b999b071e1fafab20e9ad2b5d25d675c/js/thumbnails.js#L12
</details>

Нужно доработать функции, чтобы она могла принимать массив с фото как аргумент, а не напрямую в модуле (через замыкание).

Ожидание:

```js
// main.js
const photos = createPhotoDescriptions();

renderThumbnails(photos);
```
https://github.com/htmlacademy-javascript/2058165-kekstagram-28/blob/4ebe36e7b999b071e1fafab20e9ad2b5d25d675c/js/thumbnails.js#L8

После доработки это нужно удалить.

2023-03-18 13:37 UTC, AlexMasterov commented on js/thumbnails.js
> +
<details>
<summary>thumbnails.js</summary>

https://github.com/htmlacademy-javascript/2058165-kekstagram-28/blob/4ebe36e7b999b071e1fafab20e9ad2b5d25d675c/js/thumbnails.js#L3-L6
</details>

<details>
<summary>thumbnails.js</summary>

https://github.com/htmlacademy-javascript/2058165-kekstagram-28/blob/4ebe36e7b999b071e1fafab20e9ad2b5d25d675c/js/thumbnails.js#L15
</details>

Если в одном случае был использован суффикс `Element`, то он должен использоваться для всех переменных, которые указывают на DOM-элементы (= объекты типа `Element`). В ином случае такой суффикс можно не использовать.

[Д6](https://up.htmlacademy.ru/javascript/28/criteries#d6) 
> Используется единый стиль именования переменных

> если переменные, которые хранят DOM-элемент, содержат слово `Element` или любое другое, но одно и то же везде

Нужно _для всего_ проекта определиться с форматом именования переменных, которые указывают на DOM-элементы.

2023-03-18 13:41 UTC, AlexMasterov commented on js/thumbnails.js
> +  pictureDescriptions.forEach((photo) => {
<details>
<summary>thumbnails.js</summary>

https://github.com/htmlacademy-javascript/2058165-kekstagram-28/blob/4ebe36e7b999b071e1fafab20e9ad2b5d25d675c/js/thumbnails.js#L14-L20
</details>

```js
const { id, url, description, likes, comments } = photo;

// ...
```

2023-03-20 08:46 UTC, ya-broccoli commented on js/thumbnails.js
> +  pictureDescriptions.forEach((photo) => {
👀

2023-03-20 09:32 UTC, AlexMasterov commented
👍🏻

2023-03-20 09:32 UTC, merged